# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d0b3633aa7436c9a48da97601ac50d82af144e080ee3c3ee17dc95fe916be5a415751a5f8709500f67be99db7eb0cffa1ce0d1103302643e7ccdbddc3badbda

test:
  secret_key_base: 8ff0720ee671a0cef042699f4043de0f802e91c891d690fc31f4952b25aff5e4218b51e7039602c1d1d4f7fb17ae520bb40e3511eae4c766251b5cd05bd9ea67

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
